import type { Template } from "./types"

export const templates: Template[] = [
  {
    id: "modern",
    name: "Modern Blue",
    description: "Clean and contemporary design with blue accents",
    image: "/templates/modern.webp",
    category: "modern",
    requiresPhoto: true,
  },
  {
    id: "tech",
    name: "Tech Professional",
    description: "Perfect for developers and tech professionals",
    image: "/templates/tech.jpg",
    category: "modern",
    requiresPhoto: true,
  },
  {
    id: "elegant",
    name: "Elegant Minimal",
    description: "Sophisticated and minimalist design",
    image: "/templates/elegant.webp",
    category: "minimal",
    requiresPhoto: false,
  },
  {
    id: "classic",
    name: "Classic Professional",
    description: "Traditional and timeless layout",
    image: "/templates/classic.jpg",
    category: "classic",
    requiresPhoto: false,
  },
  {
    id: "bold",
    name: "Bold Creative",
    description: "Eye-catching design for creative professionals",
    image: "/templates/bold.jpg",
    category: "creative",
    requiresPhoto: true,
  },
  {
    id: "professional",
    name: "Corporate Professional",
    description: "Perfect for corporate environments",
    image: "/templates/professional.avif",
    category: "classic",
    requiresPhoto: false,
  },
  {
    id: "minimal",
    name: "Ultra Minimal",
    description: "Clean and simple design",
    image: "/templates/minimal.avif",
    category: "minimal",
    requiresPhoto: false,
  },
  {
    id: "creative",
    name: "Creative Portfolio",
    description: "Unique design for creative fields",
    image: "/templates/creative.avif",
    category: "creative",
    requiresPhoto: true,
  },
  {
    id: "clean",
    name: "Clean Professional",
    description: "Simple and professional layout",
    image: "/templates/clean.png",
    category: "classic",
    requiresPhoto: false,
  },
]
